# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Eage.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1126, 860)
        self.OpenButton = QtWidgets.QPushButton(Dialog)
        self.OpenButton.setGeometry(QtCore.QRect(230, 690, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.OpenButton.setFont(font)
        self.OpenButton.setObjectName("OpenButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(280, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(740, 50, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ProcessButton = QtWidgets.QPushButton(Dialog)
        self.ProcessButton.setGeometry(QtCore.QRect(660, 690, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.ProcessButton.setFont(font)
        self.ProcessButton.setObjectName("ProcessButton")
        self.SaveButton = QtWidgets.QPushButton(Dialog)
        self.SaveButton.setGeometry(QtCore.QRect(830, 690, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.SaveButton.setFont(font)
        self.SaveButton.setObjectName("SaveButton")
        self.inputimage = QtWidgets.QLabel(Dialog)
        self.inputimage.setGeometry(QtCore.QRect(111, 104, 401, 521))
        self.inputimage.setStyleSheet("border:1px solid rgb(0,0,0)")
        self.inputimage.setObjectName("inputimage")
        self.outputimage = QtWidgets.QLabel(Dialog)
        self.outputimage.setGeometry(QtCore.QRect(620, 100, 401, 531))
        self.outputimage.setStyleSheet("border:1px solid rgb(0,0,0)")
        self.outputimage.setObjectName("outputimage")
        self.CameraButton = QtWidgets.QPushButton(Dialog)
        self.CameraButton.setGeometry(QtCore.QRect(480, 780, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.CameraButton.setFont(font)
        self.CameraButton.setObjectName("CameraButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.OpenButton.setText(_translate("Dialog", "Open"))
        self.label.setText(_translate("Dialog", "Input"))
        self.label_2.setText(_translate("Dialog", "Age Estimation"))
        self.ProcessButton.setText(_translate("Dialog", "Process"))
        self.SaveButton.setText(_translate("Dialog", "Save"))
        self.inputimage.setText(_translate("Dialog", "input image"))
        self.outputimage.setText(_translate("Dialog", "output image"))
        self.CameraButton.setText(_translate("Dialog", "Camera"))
